export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_LOADING_ERROR = 'POSTS_LOADING_ERROR';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POST_CREATED = 'POST_CREATED';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_DELETED = 'POST_DELETED';