export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_LOADING_ERROR = 'POSTS_LOADING_ERROR';
export const POSTS_LOADED = 'POSTS_LOADED';

export const POST_LOADING = 'POST_LOADING';
export const POST_LOADING_ERROR = 'POST_LOADING_ERROR';
export const POST_LOADED = 'POST_LOADED';
