export const POSTS_LOADING = 'POST_LOADING';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_ERROR = 'POSTS_ERROR';

export const POST_LOADED = 'POST_LOADED';
export const POST_CREATED = 'POST_CREATED';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_DELETED = 'POST_DELETED';

export const COMMENTS_LOADED = 'COMMENTS_LOADED';

export const COMMENT_CREATED = 'COMMENT_CREATED'; 
export const COMMENT_UPDATED = 'COMMENT_UPDATED';
export const COMMENT_DELETED = 'COMMENT_DELETED;'